version: '3.6'
services:
  nginx:
    image: nginx
    depends_on:
      - netbox
    ports:
      - '8000:8000'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
  netbox:
    build:
      context: ../
      dockerfile: develop/Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - ./dev.env
    volumes:
      - ./config:/etc/netbox/config:z,ro
    depends_on:
      - netbox-worker
      - postgres
      - redis
  netbox-worker:
    build:
      context: ../
      dockerfile: develop/Dockerfile
    env_file:
      - ./dev.env
    volumes:
      - ./config:/etc/netbox/config:z,ro
    depends_on:
      - redis
      - postgres
    command:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
      - rqworker
  netbox-housekeeping:
    build:
      context: ../
      dockerfile: develop/Dockerfile
    env_file:
      - ./dev.env
    volumes:
      - ./config:/etc/netbox/config:z,ro
    depends_on:
      - redis
      - postgres
    command:
      - /opt/netbox/housekeeping.sh
  postgres:
    image: postgres:13-alpine
    env_file:
      - ./dev.env
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    command:
      - sh
      - -c  # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD  ## $$ because of docker-compose
    env_file:
      - ./dev.env
    volumes:
      - netbox-redis-data:/data

volumes:
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
